import { ChecklistTemplate } from '../types';

export const CHECKLIST_TEMPLATES: ChecklistTemplate[] = [
  {
    id: 'tpl-inspeccion-ocular',
    name: 'Inspección ocular',
    icon: '🔍',
    items: [
      'Asegurar el perímetro y acordonar el lugar',
      'Registrar hora de llegada y personal presente',
      'Fotografiar panorámica general del lugar',
      'Fotografiar detalle de evidencias en su posición original',
      'Esquematizar el lugar (croquis) con medidas',
      'Recolectar elementos materiales de prueba (EMP)',
      'Embalar EMP con registro de cadena de custodia',
      'Rotular cada EMP con código único',
      'Entrevistar testigos presenciales iniciales',
      'Registrar condiciones climáticas y de iluminación',
      'Documentar modificaciones realizadas en el lugar',
    ],
  },
  {
    id: 'tpl-entrevista-testigo',
    name: 'Entrevista a testigo',
    icon: '🎙',
    items: [
      'Identificación plena del entrevistado (cédula, dirección, teléfono)',
      'Advertir de los derechos del testigo (Art. 394 CPP)',
      'Registrar lugar y hora de la entrevista',
      'Preguntar sobre relación con hechos o partes',
      'Preguntas abiertas antes que cerradas',
      'Registrar descripción cronológica libre',
      'Profundizar con preguntas específicas (qué, cómo, cuándo, dónde, quiénes)',
      'Descripción física de personas mencionadas',
      'Ubicación exacta de objetos mencionados',
      'Confirmar disponibilidad futura del testigo',
      'Lectura y firma del acta por el entrevistado',
    ],
  },
  {
    id: 'tpl-captura-flagrancia',
    name: 'Captura en flagrancia',
    icon: '🚔',
    items: [
      'Verificar que los hechos cumplan los 3 criterios de flagrancia (Art. 301 CPP)',
      'Identificar al capturado (nombre, documento)',
      'Leer los derechos al capturado',
      'Registrar hora exacta de la captura',
      'Realizar registro personal si procede',
      'Consignar objetos incautados con cadena de custodia',
      'Fotografiar al capturado con fecha/hora',
      'Trasladar al URI dentro de las 36 horas',
      'Poner a disposición del Fiscal URI',
      'Diligenciar informe de captura',
      'Llenar acta de derechos del capturado',
    ],
  },
  {
    id: 'tpl-cadena-custodia',
    name: 'Cadena de custodia (EMP)',
    icon: '🔗',
    items: [
      'Identificar el EMP en el lugar de los hechos',
      'Fotografía del EMP en su posición original',
      'Fotografía con testigo métrico (regla) al lado',
      'Recolección usando herramientas adecuadas (guantes, pinzas)',
      'Embalaje en contenedor apropiado (bolsa, frasco, sobre)',
      'Sellado y rotulado con código único',
      'Diligenciamiento del formato de cadena de custodia',
      'Registro de cada traspaso (nombre, entidad, fecha, hora)',
      'Transporte seguro al laboratorio o bodega de evidencias',
      'Confirmación de recepción firmada por destinatario',
    ],
  },
  {
    id: 'tpl-allanamiento',
    name: 'Allanamiento y registro',
    icon: '🏠',
    items: [
      'Verificar orden judicial vigente y específica',
      'Revisar coordenadas exactas del inmueble',
      'Planeación de seguridad del procedimiento',
      'Llegada al lugar y identificación como Policía Judicial',
      'Exhibir orden al morador',
      'Realizar registro metódico habitación por habitación',
      'Fotografiar áreas y evidencias',
      'Incautar EMP con cadena de custodia',
      'Registrar daños causados si los hay',
      'Elaborar acta con firmas de morador y testigos',
      'Entregar copia del acta al morador',
    ],
  },
  {
    id: 'tpl-interrogatorio-indiciado',
    name: 'Interrogatorio a indiciado',
    icon: '💬',
    items: [
      'Verificar presencia de abogado defensor',
      'Lectura de derechos del indiciado',
      'Registrar identificación plena',
      'Grabación audiovisual del interrogatorio',
      'Preguntas concretas sobre los hechos',
      'No intimidación ni promesas',
      'Registrar preguntas y respuestas textualmente',
      'Permitir al indiciado revisar las respuestas',
      'Firma del acta por indiciado, defensor e investigador',
    ],
  },
];
