export const Strings = {
  appName: 'Gestión Documental',
  tabs: {
    home: 'Inicio',
    templates: 'Plantillas',
    documents: 'Documentos',
    profile: 'Perfil',
  },
  profile: {
    title: 'Mi Perfil',
    setup: 'Configurar Perfil',
    setupSubtitle: 'Ingresa tus datos. Aparecerán automáticamente en todos los documentos.',
    fullName: 'Nombre completo',
    rank: 'Grado',
    position: 'Cargo',
    unit: 'Unidad / Dependencia',
    signature: 'Firma digital',
    drawSignature: 'Dibujar firma',
    clearSignature: 'Limpiar',
    saveProfile: 'Guardar Perfil',
    editProfile: 'Editar Perfil',
    signaturePlaceholder: 'Toca aquí para dibujar tu firma',
    profileSaved: 'Perfil guardado correctamente',
  },
  templates: {
    title: 'Plantillas',
    empty: 'No tienes plantillas guardadas',
    emptySubtitle: 'Crea una nueva plantilla o sube un documento',
    create: 'Crear plantilla',
    upload: 'Subir documento',
    nameLabel: 'Nombre de la plantilla',
    descriptionLabel: 'Descripción (opcional)',
    selectFile: 'Seleccionar archivo',
    detectingFields: 'Detectando campos...',
    fieldsDetected: 'Campos detectados',
    noFieldsDetected: 'No se detectaron campos automáticamente',
    addField: 'Agregar campo',
    fieldLabel: 'Etiqueta del campo',
    fieldType: 'Tipo de campo',
    saveTemplate: 'Guardar Plantilla',
    deleteConfirm: '¿Eliminar esta plantilla? Los documentos existentes no se verán afectados.',
    confirmDelete: 'Eliminar',
    cancel: 'Cancelar',
    uploadHint: 'Formatos soportados: .docx, .txt, .html',
  },
  documents: {
    title: 'Documentos',
    empty: 'No tienes documentos guardados',
    emptySubtitle: 'Crea un nuevo documento desde una plantilla',
    newDocument: 'Nuevo Oficio',
    saveDraft: 'Guardar Borrador',
    finalize: 'Finalizar',
    preview: 'Vista Previa',
    exportPdf: 'Exportar PDF',
    editDocument: 'Editar',
    status: {
      draft: 'Borrador',
      complete: 'Completo',
      exported: 'Exportado',
    },
    naturalPersons: 'Personas Naturales',
    legalPersons: 'Personas Jurídicas',
    addNaturalPerson: 'Agregar persona natural',
    addLegalPerson: 'Agregar persona jurídica',
    personName: 'Nombre y Apellidos',
    cedula: 'Cédula',
    companyName: 'Nombre de la empresa',
    nit: 'NIT',
    documentTitle: 'Título del documento',
    deleteConfirm: '¿Eliminar este documento?',
    autoFilledFromProfile: 'Completado desde tu perfil',
    editInProfile: 'Editar en Perfil',
  },
  home: {
    recentDocuments: 'Documentos recientes',
    noRecentDocuments: 'No hay documentos recientes',
    quickActions: 'Acciones rápidas',
    newDocument: 'Nuevo Oficio',
    uploadTemplate: 'Subir Plantilla',
    selectTemplate: 'Selecciona una plantilla',
  },
  common: {
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    back: 'Atrás',
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    required: 'Este campo es obligatorio',
    optional: 'Opcional',
    unnamed: 'Sin nombre',
    city: 'Bogotá D.C.',
  },
  fieldTypes: {
    text: 'Texto',
    multiline: 'Texto largo',
    date: 'Fecha',
    natural_persons_table: 'Tabla personas naturales',
    legal_persons_table: 'Tabla personas jurídicas',
    signature: 'Firma',
    investigator_name: 'Nombre del investigador',
    investigator_rank: 'Grado del investigador',
  },
};
